### ISSUE TITLE
1M repeating intervals at the end of the month

### ISSUE THREAD

**Issue by deatheragetr** [SebastianEdwards/time-interval#1]
Hope this is an okay place to ask a question: 
When parsing repeating 1M intervals that begin at the end of month (say January 31st), I've had difficulty finding any conclusive description on the most proper way of counting the duration of "1M".  Different places seem to do this differently.  For example, time-interval does it like this: https://gist.github.com/deatheragetr/8c6534d86726ad13e35d

Whereas perl's DateTime does it a bit differently:
https://gist.github.com/deatheragetr/83fbf8f458a7e4b52de1

This seems perfectly sensible, but hardly universal.  Do you have any source supporting your approach over others?

**Comment by SebastianEdwards** [comment]
RE the approach taken: I completely defer to ActiveSupport to handle time arithmetic so it may be best to take up the question there.

Your example does highlight an issue in my logic: the start time for months following Feb should not be locked at the 28th. Rather than generating periods by adding 1 month to the previous period it would be better if I add `n` months to the initial period (where `n` is the period index).

```
Time.new(2015,1,31) + 1.month # => 2015-02-28 00:00:00 +1300
Time.new(2015,1,31) + 2.month # => 2015-03-31 00:00:00 +1300
Time.new(2015,1,31) + 3.month # => 2015-04-30 00:00:00 +1200
Time.new(2015,1,31) + 4.month # => 2015-05-31 00:00:00 +1200
```

This way if an interval starts on the 31st then new periods should always begin on the last day of the month. This, unfortunately, is the closest one can come to specifying "the last day of the month" in ISO8601.

Thanks for taking the time to submit this issue!

**Comment by deatheragetr** [comment]
Cool -- I agree with that.

Thanks!
